server:
  context-path: "/small"
  port: 9191

mq:
  broker:
    url: "failover:(tcp://localhost:61616)"
  queue:
    story: "com.chawin.small.story"
    history: "com.chawin.small.history"

spring:
  profiles:
    active: production
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/movie_master
    username: chawintyan
    password: chawin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

